# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jpeg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/images-interface-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.textCurrentFile = QtWidgets.QLineEdit(self.centralwidget)
        self.textCurrentFile.setEnabled(False)
        self.textCurrentFile.setInputMask("")
        self.textCurrentFile.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFile.setReadOnly(True)
        self.textCurrentFile.setObjectName("textCurrentFile")
        self.verticalLayout_8.addWidget(self.textCurrentFile)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/buildings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_1.setIcon(icon1)
        self.radioButton_1.setIconSize(QtCore.QSize(40, 40))
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setIcon(icon)
        self.radioButton_2.setIconSize(QtCore.QSize(40, 40))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/page-interface-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_3.setIcon(icon2)
        self.radioButton_3.setIconSize(QtCore.QSize(40, 40))
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1258, 623))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.img1_1 = QtWidgets.QLabel(self.page)
        self.img1_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_1.setText("")
        self.img1_1.setScaledContents(True)
        self.img1_1.setObjectName("img1_1")
        self.gridLayout_2.addWidget(self.img1_1, 0, 0, 1, 1)
        self.img1_2 = QtWidgets.QLabel(self.page)
        self.img1_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_2.setText("")
        self.img1_2.setScaledContents(True)
        self.img1_2.setObjectName("img1_2")
        self.gridLayout_2.addWidget(self.img1_2, 0, 1, 1, 1)
        self.img1_3 = QtWidgets.QLabel(self.page)
        self.img1_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_3.setText("")
        self.img1_3.setScaledContents(True)
        self.img1_3.setObjectName("img1_3")
        self.gridLayout_2.addWidget(self.img1_3, 0, 2, 1, 1)
        self.img1_4 = QtWidgets.QLabel(self.page)
        self.img1_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_4.setScaledContents(True)
        self.img1_4.setObjectName("img1_4")
        self.gridLayout_2.addWidget(self.img1_4, 0, 3, 1, 1)
        self.img1_5 = QtWidgets.QLabel(self.page)
        self.img1_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_5.setText("")
        self.img1_5.setScaledContents(True)
        self.img1_5.setObjectName("img1_5")
        self.gridLayout_2.addWidget(self.img1_5, 1, 0, 1, 1)
        self.img1_6 = QtWidgets.QLabel(self.page)
        self.img1_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_6.setText("")
        self.img1_6.setScaledContents(True)
        self.img1_6.setObjectName("img1_6")
        self.gridLayout_2.addWidget(self.img1_6, 1, 1, 1, 1)
        self.img1_7 = QtWidgets.QLabel(self.page)
        self.img1_7.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.img1_7.setText("")
        self.img1_7.setScaledContents(True)
        self.img1_7.setObjectName("img1_7")
        self.gridLayout_2.addWidget(self.img1_7, 1, 2, 1, 1)
        self.img1_8 = QtWidgets.QLabel(self.page)
        self.img1_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_8.setText("")
        self.img1_8.setScaledContents(True)
        self.img1_8.setObjectName("img1_8")
        self.gridLayout_2.addWidget(self.img1_8, 1, 3, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img1_9 = QtWidgets.QLabel(self.page_4)
        self.img1_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_9.setText("")
        self.img1_9.setScaledContents(True)
        self.img1_9.setObjectName("img1_9")
        self.verticalLayout_2.addWidget(self.img1_9)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img1_10 = QtWidgets.QLabel(self.page_5)
        self.img1_10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_10.setText("")
        self.img1_10.setScaledContents(True)
        self.img1_10.setObjectName("img1_10")
        self.verticalLayout_3.addWidget(self.img1_10)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img1_11 = QtWidgets.QLabel(self.page_6)
        self.img1_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_11.setText("")
        self.img1_11.setScaledContents(True)
        self.img1_11.setObjectName("img1_11")
        self.verticalLayout_4.addWidget(self.img1_11)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.img1_12 = QtWidgets.QLabel(self.page_7)
        self.img1_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_12.setText("")
        self.img1_12.setScaledContents(True)
        self.img1_12.setObjectName("img1_12")
        self.verticalLayout_5.addWidget(self.img1_12)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.img1_13 = QtWidgets.QLabel(self.page_8)
        self.img1_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_13.setText("")
        self.img1_13.setScaledContents(True)
        self.img1_13.setObjectName("img1_13")
        self.verticalLayout_6.addWidget(self.img1_13)
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.img1_14 = QtWidgets.QLabel(self.page_9)
        self.img1_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_14.setText("")
        self.img1_14.setScaledContents(True)
        self.img1_14.setObjectName("img1_14")
        self.verticalLayout_7.addWidget(self.img1_14)
        self.stackedWidget_2.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.img1_15 = QtWidgets.QLabel(self.page_10)
        self.img1_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_15.setText("")
        self.img1_15.setScaledContents(True)
        self.img1_15.setObjectName("img1_15")
        self.verticalLayout_9.addWidget(self.img1_15)
        self.stackedWidget_2.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.img1_16 = QtWidgets.QLabel(self.page_11)
        self.img1_16.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_16.setText("")
        self.img1_16.setScaledContents(True)
        self.img1_16.setObjectName("img1_16")
        self.verticalLayout_10.addWidget(self.img1_16)
        self.stackedWidget_2.addWidget(self.page_11)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        self.horizontalSlider = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(7)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dockWidget_2 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img1_17 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.img1_17.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_17.setText("")
        self.img1_17.setScaledContents(True)
        self.img1_17.setObjectName("img1_17")
        self.horizontalLayout_3.addWidget(self.img1_17)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.dockWidget_2)
        self.dockWidget_3 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.img1_18 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.img1_18.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_18.setText("")
        self.img1_18.setScaledContents(True)
        self.img1_18.setObjectName("img1_18")
        self.horizontalLayout_4.addWidget(self.img1_18)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.dockWidget_3)
        self.dockWidget_4 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_4.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_4.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img1_19 = QtWidgets.QLabel(self.dockWidgetContents_4)
        self.img1_19.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_19.setText("")
        self.img1_19.setScaledContents(True)
        self.img1_19.setObjectName("img1_19")
        self.horizontalLayout_5.addWidget(self.img1_19)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.dockWidget_4)
        self.dockWidget_5 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_5.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_5.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dockWidgetContents_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.img1_20 = QtWidgets.QLabel(self.dockWidgetContents_6)
        self.img1_20.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_20.setText("")
        self.img1_20.setScaledContents(True)
        self.img1_20.setObjectName("img1_20")
        self.horizontalLayout_6.addWidget(self.img1_20)
        self.dockWidget_5.setWidget(self.dockWidgetContents_6)
        self.horizontalLayout_2.addWidget(self.dockWidget_5)
        self.dockWidget_6 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_6.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_6.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.dockWidgetContents_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.img1_21 = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.img1_21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_21.setText("")
        self.img1_21.setScaledContents(True)
        self.img1_21.setObjectName("img1_21")
        self.horizontalLayout_7.addWidget(self.img1_21)
        self.dockWidget_6.setWidget(self.dockWidgetContents_7)
        self.horizontalLayout_2.addWidget(self.dockWidget_6)
        self.dockWidget_7 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_7.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_7.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_7.setObjectName("dockWidget_7")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.dockWidgetContents_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.img1_22 = QtWidgets.QLabel(self.dockWidgetContents_8)
        self.img1_22.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_22.setText("")
        self.img1_22.setScaledContents(True)
        self.img1_22.setObjectName("img1_22")
        self.horizontalLayout_8.addWidget(self.img1_22)
        self.dockWidget_7.setWidget(self.dockWidgetContents_8)
        self.horizontalLayout_2.addWidget(self.dockWidget_7)
        self.dockWidget_8 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_8.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_8.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_8.setObjectName("dockWidget_8")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.dockWidgetContents_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.img1_23 = QtWidgets.QLabel(self.dockWidgetContents_9)
        self.img1_23.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_23.setText("")
        self.img1_23.setScaledContents(True)
        self.img1_23.setObjectName("img1_23")
        self.horizontalLayout_9.addWidget(self.img1_23)
        self.dockWidget_8.setWidget(self.dockWidgetContents_9)
        self.horizontalLayout_2.addWidget(self.dockWidget_8)
        self.dockWidget_9 = QtWidgets.QDockWidget(self.page_3)
        self.dockWidget_9.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_9.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_9.setObjectName("dockWidget_9")
        self.dockWidgetContents_10 = QtWidgets.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.dockWidgetContents_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.img1_24 = QtWidgets.QLabel(self.dockWidgetContents_10)
        self.img1_24.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1_24.setText("")
        self.img1_24.setScaledContents(True)
        self.img1_24.setObjectName("img1_24")
        self.horizontalLayout_10.addWidget(self.img1_24)
        self.dockWidget_9.setWidget(self.dockWidgetContents_10)
        self.horizontalLayout_2.addWidget(self.dockWidget_9)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(7)
        self.pushButton.clicked.connect(MainWindow.load_image)
        self.horizontalSlider.valueChanged['int'].connect(self.stackedWidget_2.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JPEG Decoder"))
        self.pushButton.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFile.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFile.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox.setTitle(_translate("MainWindow", "View Style"))
        self.radioButton_1.setText(_translate("MainWindow", "Grid View"))
        self.radioButton_1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.radioButton_2.setText(_translate("MainWindow", "Stacked View with Slider"))
        self.radioButton_2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.radioButton_3.setText(_translate("MainWindow", "Docked Horizontally"))
        self.radioButton_3.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "12.5% Decoded"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "25% Decoded"))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "37.5% Decoded"))
        self.dockWidget_5.setWindowTitle(_translate("MainWindow", "50% Decoded"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "62.5% Decoded"))
        self.dockWidget_7.setWindowTitle(_translate("MainWindow", "75% Decoded"))
        self.dockWidget_8.setWindowTitle(_translate("MainWindow", "87.5% Decoded"))
        self.dockWidget_9.setWindowTitle(_translate("MainWindow", "100% Decoded"))

