# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperStar.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Guitar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Guitar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/23469-NVFW8H.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Guitar.setIcon(icon)
        self.pushButton_Guitar.setIconSize(QtCore.QSize(300, 800))
        self.pushButton_Guitar.setFlat(True)
        self.pushButton_Guitar.setObjectName("pushButton_Guitar")
        self.gridLayout.addWidget(self.pushButton_Guitar, 1, 0, 1, 1)
        self.labelPIANO = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(28)
        self.labelPIANO.setFont(font)
        self.labelPIANO.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPIANO.setObjectName("labelPIANO")
        self.gridLayout.addWidget(self.labelPIANO, 2, 1, 1, 1)
        self.labelGUITAR = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(28)
        self.labelGUITAR.setFont(font)
        self.labelGUITAR.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGUITAR.setObjectName("labelGUITAR")
        self.gridLayout.addWidget(self.labelGUITAR, 2, 0, 1, 1)
        self.labelSuperStar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(48)
        self.labelSuperStar.setFont(font)
        self.labelSuperStar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSuperStar.setObjectName("labelSuperStar")
        self.gridLayout.addWidget(self.labelSuperStar, 0, 0, 1, 2)
        self.pushButton_Piano = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Piano.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/23469-NVFW8K.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Piano.setIcon(icon1)
        self.pushButton_Piano.setIconSize(QtCore.QSize(300, 800))
        self.pushButton_Piano.setFlat(True)
        self.pushButton_Piano.setObjectName("pushButton_Piano")
        self.gridLayout.addWidget(self.pushButton_Piano, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(1270, 470))
        self.dockWidget.setMaximumSize(QtCore.QSize(1270, 470))
        self.dockWidget.setFloating(True)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.GUITAR_BODY = QtWidgets.QPushButton(self.dockWidgetContents)
        self.GUITAR_BODY.setEnabled(True)
        self.GUITAR_BODY.setGeometry(QtCore.QRect(0, 0, 1270, 470))
        self.GUITAR_BODY.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/23469-NVFW8G.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GUITAR_BODY.setIcon(icon2)
        self.GUITAR_BODY.setIconSize(QtCore.QSize(1270, 470))
        self.GUITAR_BODY.setFlat(True)
        self.GUITAR_BODY.setObjectName("GUITAR_BODY")
        self.th_6 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_6.setGeometry(QtCore.QRect(229, 252, 283, 9))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_6.setIcon(icon3)
        self.th_6.setIconSize(QtCore.QSize(283, 9))
        self.th_6.setFlat(True)
        self.th_6.setObjectName("th_6")
        self.th_1 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_1.setGeometry(QtCore.QRect(228, 207, 283, 8))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_1.setIcon(icon4)
        self.th_1.setIconSize(QtCore.QSize(283, 8))
        self.th_1.setFlat(True)
        self.th_1.setObjectName("th_1")
        self.th_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_2.setGeometry(QtCore.QRect(245, 215, 267, 9))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_2.setIcon(icon5)
        self.th_2.setIconSize(QtCore.QSize(267, 9))
        self.th_2.setFlat(True)
        self.th_2.setObjectName("th_2")
        self.th_3 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_3.setGeometry(QtCore.QRect(260, 224, 252, 9))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_3.setIcon(icon6)
        self.th_3.setIconSize(QtCore.QSize(252, 9))
        self.th_3.setFlat(True)
        self.th_3.setObjectName("th_3")
        self.th_5 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_5.setGeometry(QtCore.QRect(245, 243, 267, 9))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_5.setIcon(icon7)
        self.th_5.setIconSize(QtCore.QSize(267, 9))
        self.th_5.setFlat(True)
        self.th_5.setObjectName("th_5")
        self.th_4 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.th_4.setGeometry(QtCore.QRect(260, 234, 252, 9))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.th_4.setIcon(icon8)
        self.th_4.setIconSize(QtCore.QSize(252, 9))
        self.th_4.setFlat(True)
        self.th_4.setObjectName("th_4")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(209, 203, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(226, 212, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(209, 249, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(226, 240, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(241, 231, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(241, 221, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName("label_6")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(1270, 543))
        self.dockWidget_3.setMaximumSize(QtCore.QSize(1270, 543))
        self.dockWidget_3.setFloating(True)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.PIANO_BODY = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.PIANO_BODY.setEnabled(True)
        self.PIANO_BODY.setGeometry(QtCore.QRect(0, 0, 1270, 543))
        self.PIANO_BODY.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/49373 [Converted].png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PIANO_BODY.setIcon(icon9)
        self.PIANO_BODY.setIconSize(QtCore.QSize(1270, 543))
        self.PIANO_BODY.setFlat(True)
        self.PIANO_BODY.setObjectName("PIANO_BODY")
        self.bt_1 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_1.setGeometry(QtCore.QRect(16, 272, 73, 254))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_1.setIcon(icon10)
        self.bt_1.setIconSize(QtCore.QSize(73, 254))
        self.bt_1.setFlat(True)
        self.bt_1.setObjectName("bt_1")
        self.bt_6 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_6.setGeometry(QtCore.QRect(266, 272, 73, 254))
        self.bt_6.setIcon(icon10)
        self.bt_6.setIconSize(QtCore.QSize(73, 254))
        self.bt_6.setFlat(True)
        self.bt_6.setObjectName("bt_6")
        self.bt_11 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_11.setGeometry(QtCore.QRect(517, 272, 73, 254))
        self.bt_11.setIcon(icon10)
        self.bt_11.setIconSize(QtCore.QSize(73, 254))
        self.bt_11.setFlat(True)
        self.bt_11.setObjectName("bt_11")
        self.bt_16 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_16.setGeometry(QtCore.QRect(768, 272, 73, 254))
        self.bt_16.setIcon(icon10)
        self.bt_16.setIconSize(QtCore.QSize(73, 254))
        self.bt_16.setFlat(True)
        self.bt_16.setObjectName("bt_16")
        self.bt_21 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_21.setGeometry(QtCore.QRect(1019, 272, 73, 254))
        self.bt_21.setIcon(icon10)
        self.bt_21.setIconSize(QtCore.QSize(73, 254))
        self.bt_21.setFlat(True)
        self.bt_21.setObjectName("bt_21")
        self.bt_2 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_2.setGeometry(QtCore.QRect(64, 272, 50, 144))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_2.setIcon(icon11)
        self.bt_2.setIconSize(QtCore.QSize(50, 144))
        self.bt_2.setFlat(True)
        self.bt_2.setObjectName("bt_2")
        self.bt_4 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_4.setGeometry(QtCore.QRect(145, 272, 50, 144))
        self.bt_4.setIcon(icon11)
        self.bt_4.setIconSize(QtCore.QSize(50, 144))
        self.bt_4.setFlat(True)
        self.bt_4.setObjectName("bt_4")
        self.bt_7 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_7.setGeometry(QtCore.QRect(315, 272, 50, 144))
        self.bt_7.setIcon(icon11)
        self.bt_7.setIconSize(QtCore.QSize(50, 144))
        self.bt_7.setFlat(True)
        self.bt_7.setObjectName("bt_7")
        self.bt_9 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_9.setGeometry(QtCore.QRect(396, 272, 50, 144))
        self.bt_9.setIcon(icon11)
        self.bt_9.setIconSize(QtCore.QSize(50, 144))
        self.bt_9.setFlat(True)
        self.bt_9.setObjectName("bt_9")
        self.bt_12 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_12.setGeometry(QtCore.QRect(565, 272, 50, 144))
        self.bt_12.setIcon(icon11)
        self.bt_12.setIconSize(QtCore.QSize(50, 144))
        self.bt_12.setFlat(True)
        self.bt_12.setObjectName("bt_12")
        self.bt_14 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_14.setGeometry(QtCore.QRect(646, 272, 50, 144))
        self.bt_14.setIcon(icon11)
        self.bt_14.setIconSize(QtCore.QSize(50, 144))
        self.bt_14.setFlat(True)
        self.bt_14.setObjectName("bt_14")
        self.bt_17 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_17.setGeometry(QtCore.QRect(816, 272, 50, 144))
        self.bt_17.setIcon(icon11)
        self.bt_17.setIconSize(QtCore.QSize(50, 144))
        self.bt_17.setFlat(True)
        self.bt_17.setObjectName("bt_17")
        self.bt_19 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_19.setGeometry(QtCore.QRect(897, 272, 50, 144))
        self.bt_19.setIcon(icon11)
        self.bt_19.setIconSize(QtCore.QSize(50, 144))
        self.bt_19.setFlat(True)
        self.bt_19.setObjectName("bt_19")
        self.bt_22 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_22.setGeometry(QtCore.QRect(1067, 272, 50, 144))
        self.bt_22.setIcon(icon11)
        self.bt_22.setIconSize(QtCore.QSize(50, 144))
        self.bt_22.setFlat(True)
        self.bt_22.setObjectName("bt_22")
        self.bt_24 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_24.setGeometry(QtCore.QRect(1147, 272, 50, 144))
        self.bt_24.setIcon(icon11)
        self.bt_24.setIconSize(QtCore.QSize(50, 144))
        self.bt_24.setFlat(True)
        self.bt_24.setObjectName("bt_24")
        self.bt_5 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_5.setGeometry(QtCore.QRect(178, 272, 74, 254))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/05.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_5.setIcon(icon12)
        self.bt_5.setIconSize(QtCore.QSize(74, 254))
        self.bt_5.setFlat(True)
        self.bt_5.setObjectName("bt_5")
        self.bt_10 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_10.setGeometry(QtCore.QRect(428, 272, 74, 254))
        self.bt_10.setIcon(icon12)
        self.bt_10.setIconSize(QtCore.QSize(74, 254))
        self.bt_10.setFlat(True)
        self.bt_10.setObjectName("bt_10")
        self.bt_15 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_15.setGeometry(QtCore.QRect(679, 272, 74, 254))
        self.bt_15.setIcon(icon12)
        self.bt_15.setIconSize(QtCore.QSize(74, 254))
        self.bt_15.setFlat(True)
        self.bt_15.setObjectName("bt_15")
        self.bt_20 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_20.setGeometry(QtCore.QRect(931, 272, 74, 254))
        self.bt_20.setIcon(icon12)
        self.bt_20.setIconSize(QtCore.QSize(74, 254))
        self.bt_20.setFlat(True)
        self.bt_20.setObjectName("bt_20")
        self.bt_25 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_25.setGeometry(QtCore.QRect(1183, 272, 74, 254))
        self.bt_25.setIcon(icon12)
        self.bt_25.setIconSize(QtCore.QSize(74, 254))
        self.bt_25.setFlat(True)
        self.bt_25.setObjectName("bt_25")
        self.bt_3 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_3.setGeometry(QtCore.QRect(96, 272, 75, 254))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/03.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_3.setIcon(icon13)
        self.bt_3.setIconSize(QtCore.QSize(75, 254))
        self.bt_3.setFlat(True)
        self.bt_3.setObjectName("bt_3")
        self.bt_8 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_8.setGeometry(QtCore.QRect(347, 272, 75, 254))
        self.bt_8.setIcon(icon13)
        self.bt_8.setIconSize(QtCore.QSize(75, 254))
        self.bt_8.setFlat(True)
        self.bt_8.setObjectName("bt_8")
        self.bt_13 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_13.setGeometry(QtCore.QRect(597, 272, 75, 254))
        self.bt_13.setIcon(icon13)
        self.bt_13.setIconSize(QtCore.QSize(75, 254))
        self.bt_13.setFlat(True)
        self.bt_13.setObjectName("bt_13")
        self.bt_18 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_18.setGeometry(QtCore.QRect(848, 272, 75, 254))
        self.bt_18.setIcon(icon13)
        self.bt_18.setIconSize(QtCore.QSize(75, 254))
        self.bt_18.setFlat(True)
        self.bt_18.setObjectName("bt_18")
        self.bt_23 = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.bt_23.setGeometry(QtCore.QRect(1099, 272, 75, 254))
        self.bt_23.setIcon(icon13)
        self.bt_23.setIconSize(QtCore.QSize(75, 254))
        self.bt_23.setFlat(True)
        self.bt_23.setObjectName("bt_23")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_7.setGeometry(QtCore.QRect(80, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_8.setGeometry(QtCore.QRect(162, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_9.setGeometry(QtCore.QRect(332, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_10.setGeometry(QtCore.QRect(413, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_11.setGeometry(QtCore.QRect(582, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_12.setGeometry(QtCore.QRect(663, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_12.setPalette(palette)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_13.setGeometry(QtCore.QRect(832, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_13.setPalette(palette)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_14.setGeometry(QtCore.QRect(915, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_14.setPalette(palette)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_15.setGeometry(QtCore.QRect(1084, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_15.setPalette(palette)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_16.setGeometry(QtCore.QRect(1164, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_17.setGeometry(QtCore.QRect(30, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_18.setGeometry(QtCore.QRect(121, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_18.setPalette(palette)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_19.setGeometry(QtCore.QRect(213, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_19.setPalette(palette)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_20.setGeometry(QtCore.QRect(282, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_20.setPalette(palette)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_21.setGeometry(QtCore.QRect(373, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_22.setGeometry(QtCore.QRect(464, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_23.setGeometry(QtCore.QRect(531, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_24.setGeometry(QtCore.QRect(623, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_24.setPalette(palette)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_25.setGeometry(QtCore.QRect(715, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_25.setPalette(palette)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_26.setGeometry(QtCore.QRect(784, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_26.setPalette(palette)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_27.setGeometry(QtCore.QRect(874, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_27.setPalette(palette)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_28.setGeometry(QtCore.QRect(969, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_28.setPalette(palette)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_29.setGeometry(QtCore.QRect(1035, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_29.setPalette(palette)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_30.setGeometry(QtCore.QRect(1124, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_30.setPalette(palette)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_31.setGeometry(QtCore.QRect(1220, 300, 20, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 105, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_31.setPalette(palette)
        self.label_31.setObjectName("label_31")
        self.PIANO_BODY.raise_()
        self.bt_1.raise_()
        self.bt_6.raise_()
        self.bt_11.raise_()
        self.bt_16.raise_()
        self.bt_21.raise_()
        self.bt_5.raise_()
        self.bt_10.raise_()
        self.bt_15.raise_()
        self.bt_20.raise_()
        self.bt_25.raise_()
        self.bt_3.raise_()
        self.bt_8.raise_()
        self.bt_13.raise_()
        self.bt_18.raise_()
        self.bt_23.raise_()
        self.bt_9.raise_()
        self.bt_17.raise_()
        self.bt_2.raise_()
        self.bt_19.raise_()
        self.bt_14.raise_()
        self.bt_12.raise_()
        self.bt_22.raise_()
        self.bt_7.raise_()
        self.bt_24.raise_()
        self.bt_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)

        self.dockWidget.close()
        self.dockWidget_3.close()

        self.retranslateUi(MainWindow)
        self.pushButton_Guitar.clicked.connect(self.dockWidget.show)
        self.pushButton_Piano.clicked.connect(self.dockWidget_3.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SuperStar"))
        self.pushButton_Guitar.setShortcut(_translate("MainWindow", "R"))
        self.labelPIANO.setText(_translate("MainWindow", "PIANO [O]"))
        self.labelGUITAR.setText(_translate("MainWindow", "GUITAR [R]"))
        self.labelSuperStar.setText(_translate("MainWindow", "Are you SUPERSTAR..!"))
        self.pushButton_Piano.setShortcut(_translate("MainWindow", "O"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Guitar"))
        self.th_6.setShortcut(_translate("MainWindow", "6"))
        self.th_1.setShortcut(_translate("MainWindow", "1"))
        self.th_2.setShortcut(_translate("MainWindow", "2"))
        self.th_3.setShortcut(_translate("MainWindow", "3"))
        self.th_5.setShortcut(_translate("MainWindow", "5"))
        self.th_4.setShortcut(_translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "[1]"))
        self.label_2.setText(_translate("MainWindow", "[2]"))
        self.label_3.setText(_translate("MainWindow", "[6]"))
        self.label_4.setText(_translate("MainWindow", "[5]"))
        self.label_5.setText(_translate("MainWindow", "[4]"))
        self.label_6.setText(_translate("MainWindow", "[3]"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Piano"))
        self.bt_1.setShortcut(_translate("MainWindow", "A"))
        self.bt_6.setShortcut(_translate("MainWindow", "C"))
        self.bt_11.setShortcut(_translate("MainWindow", "H"))
        self.bt_16.setShortcut(_translate("MainWindow", ","))
        self.bt_21.setShortcut(_translate("MainWindow", "\'"))
        self.bt_2.setShortcut(_translate("MainWindow", "Z"))
        self.bt_4.setShortcut(_translate("MainWindow", "X"))
        self.bt_7.setShortcut(_translate("MainWindow", "F"))
        self.bt_9.setShortcut(_translate("MainWindow", "G"))
        self.bt_12.setShortcut(_translate("MainWindow", "N"))
        self.bt_14.setShortcut(_translate("MainWindow", "M"))
        self.bt_17.setShortcut(_translate("MainWindow", "L"))
        self.bt_19.setShortcut(_translate("MainWindow", ";"))
        self.bt_22.setShortcut(_translate("MainWindow", "1"))
        self.bt_24.setShortcut(_translate("MainWindow", "3"))
        self.bt_5.setShortcut(_translate("MainWindow", "D"))
        self.bt_10.setShortcut(_translate("MainWindow", "B"))
        self.bt_15.setShortcut(_translate("MainWindow", "K"))
        self.bt_20.setShortcut(_translate("MainWindow", "/"))
        self.bt_25.setShortcut(_translate("MainWindow", "+"))
        self.bt_3.setShortcut(_translate("MainWindow", "S"))
        self.bt_8.setShortcut(_translate("MainWindow", "V"))
        self.bt_13.setShortcut(_translate("MainWindow", "J"))
        self.bt_18.setShortcut(_translate("MainWindow", "."))
        self.bt_23.setShortcut(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "[Z]"))
        self.label_8.setText(_translate("MainWindow", "[X]"))
        self.label_9.setText(_translate("MainWindow", "[F]"))
        self.label_10.setText(_translate("MainWindow", "[G]"))
        self.label_11.setText(_translate("MainWindow", "[N]"))
        self.label_12.setText(_translate("MainWindow", "[M]"))
        self.label_13.setText(_translate("MainWindow", "[L]"))
        self.label_14.setText(_translate("MainWindow", "[;]"))
        self.label_15.setText(_translate("MainWindow", "[1]"))
        self.label_16.setText(_translate("MainWindow", "[3]"))
        self.label_17.setText(_translate("MainWindow", "[A]"))
        self.label_18.setText(_translate("MainWindow", "[S]"))
        self.label_19.setText(_translate("MainWindow", "[D]"))
        self.label_20.setText(_translate("MainWindow", "[C]"))
        self.label_21.setText(_translate("MainWindow", "[V]"))
        self.label_22.setText(_translate("MainWindow", "[B]"))
        self.label_23.setText(_translate("MainWindow", "[H]"))
        self.label_24.setText(_translate("MainWindow", "[J]"))
        self.label_25.setText(_translate("MainWindow", "[K]"))
        self.label_26.setText(_translate("MainWindow", "[,]"))
        self.label_27.setText(_translate("MainWindow", "[.]"))
        self.label_28.setText(_translate("MainWindow", "[/]"))
        self.label_29.setText(_translate("MainWindow", "[\']"))
        self.label_30.setText(_translate("MainWindow", "[5]"))
        self.label_31.setText(_translate("MainWindow", "[+]"))
        self.GUITAR_BODY.setToolTip(_translate("MainWindow", "Click on the specific keys to play!"))
        self.PIANO_BODY.setToolTip(_translate("MainWindow", "Click on the specific keys to play!"))        

