# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ICA.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/network-connection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedHome = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedHome.setObjectName("stackedHome")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.btnHomeSound = QtWidgets.QPushButton(self.Home)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/maximal-volume-audio-interface-symbol-of-a-speaker-side-view-with-lines-representing-sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHomeSound.setIcon(icon1)
        self.btnHomeSound.setIconSize(QtCore.QSize(250, 250))
        self.btnHomeSound.setFlat(True)
        self.btnHomeSound.setObjectName("btnHomeSound")
        self.gridLayout_2.addWidget(self.btnHomeSound, 0, 0, 1, 1)
        self.btnHomeSignal = QtWidgets.QPushButton(self.Home)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/lifeline-signal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHomeSignal.setIcon(icon2)
        self.btnHomeSignal.setIconSize(QtCore.QSize(250, 250))
        self.btnHomeSignal.setFlat(True)
        self.btnHomeSignal.setObjectName("btnHomeSignal")
        self.gridLayout_2.addWidget(self.btnHomeSignal, 0, 1, 1, 1)
        self.stackedHome.addWidget(self.Home)
        self.soundAnalysis = QtWidgets.QWidget()
        self.soundAnalysis.setObjectName("soundAnalysis")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.soundAnalysis)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.soundAnalysis)
        self.toolBox.setObjectName("toolBox")
        self.soundSong = QtWidgets.QWidget()
        self.soundSong.setGeometry(QtCore.QRect(0, 0, 1036, 569))
        self.soundSong.setObjectName("soundSong")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.soundSong)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnPlayMusic = QtWidgets.QPushButton(self.soundSong)
        self.btnPlayMusic.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/musical-note-symbol-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlayMusic.setIcon(icon3)
        self.btnPlayMusic.setChecked(False)
        self.btnPlayMusic.setFlat(True)
        self.btnPlayMusic.setObjectName("btnPlayMusic")
        self.gridLayout_5.addWidget(self.btnPlayMusic, 4, 2, 1, 1)
        self.btnPlayVocals = QtWidgets.QPushButton(self.soundSong)
        self.btnPlayVocals.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/usher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlayVocals.setIcon(icon4)
        self.btnPlayVocals.setChecked(False)
        self.btnPlayVocals.setFlat(True)
        self.btnPlayVocals.setObjectName("btnPlayVocals")
        self.gridLayout_5.addWidget(self.btnPlayVocals, 4, 0, 1, 1)
        self.textCurrentFile = QtWidgets.QLineEdit(self.soundSong)
        self.textCurrentFile.setEnabled(False)
        self.textCurrentFile.setInputMask("")
        self.textCurrentFile.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFile.setReadOnly(True)
        self.textCurrentFile.setObjectName("textCurrentFile")
        self.gridLayout_5.addWidget(self.textCurrentFile, 1, 0, 1, 3)
        self.btnPlay = QtWidgets.QPushButton(self.soundSong)
        self.btnPlay.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/right-arrowhead-black-triangular-shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon5)
        self.btnPlay.setChecked(False)
        self.btnPlay.setFlat(True)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout_5.addWidget(self.btnPlay, 4, 1, 1, 1)
        self.btnImportSong = QtWidgets.QPushButton(self.soundSong)
        self.btnImportSong.setObjectName("btnImportSong")
        self.gridLayout_5.addWidget(self.btnImportSong, 0, 0, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(self.soundSong)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 6, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.soundSong)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.plotSongVocals = PlotWidget(self.groupBox_8)
        self.plotSongVocals.setObjectName("plotSongVocals")
        self.horizontalLayout_8.addWidget(self.plotSongVocals)
        self.plotSongMusic = PlotWidget(self.groupBox_8)
        self.plotSongMusic.setObjectName("plotSongMusic")
        self.horizontalLayout_8.addWidget(self.plotSongMusic)
        self.gridLayout_5.addWidget(self.groupBox_8, 5, 0, 1, 3)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/musical-notes-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.soundSong, icon6, "")
        self.soundCoctail = QtWidgets.QWidget()
        self.soundCoctail.setGeometry(QtCore.QRect(0, 0, 1036, 569))
        self.soundCoctail.setObjectName("soundCoctail")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.soundCoctail)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedCoctail = QtWidgets.QStackedWidget(self.soundCoctail)
        self.stackedCoctail.setMaximumSize(QtCore.QSize(1014, 16777215))
        self.stackedCoctail.setObjectName("stackedCoctail")
        self.Mix = QtWidgets.QWidget()
        self.Mix.setObjectName("Mix")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Mix)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnImportE = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportE.sizePolicy().hasHeightForWidth())
        self.btnImportE.setSizePolicy(sizePolicy)
        self.btnImportE.setObjectName("btnImportE")
        self.horizontalLayout_6.addWidget(self.btnImportE)
        self.textCurrentFileE = QtWidgets.QLineEdit(self.groupBox_6)
        self.textCurrentFileE.setEnabled(False)
        self.textCurrentFileE.setMaximumSize(QtCore.QSize(980, 16777215))
        self.textCurrentFileE.setInputMask("")
        self.textCurrentFileE.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFileE.setReadOnly(True)
        self.textCurrentFileE.setObjectName("textCurrentFileE")
        self.horizontalLayout_6.addWidget(self.textCurrentFileE)
        self.gridLayout_9.addWidget(self.groupBox_6, 6, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnImportD = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportD.sizePolicy().hasHeightForWidth())
        self.btnImportD.setSizePolicy(sizePolicy)
        self.btnImportD.setObjectName("btnImportD")
        self.horizontalLayout_5.addWidget(self.btnImportD)
        self.textCurrentFileD = QtWidgets.QLineEdit(self.groupBox_5)
        self.textCurrentFileD.setEnabled(False)
        self.textCurrentFileD.setMaximumSize(QtCore.QSize(980, 16777215))
        self.textCurrentFileD.setInputMask("")
        self.textCurrentFileD.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFileD.setReadOnly(True)
        self.textCurrentFileD.setObjectName("textCurrentFileD")
        self.horizontalLayout_5.addWidget(self.textCurrentFileD)
        self.gridLayout_9.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioFive = QtWidgets.QRadioButton(self.groupBox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/musical-notes-sign_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioFive.setIcon(icon7)
        self.radioFive.setChecked(True)
        self.radioFive.setObjectName("radioFive")
        self.horizontalLayout.addWidget(self.radioFive)
        self.radioFour = QtWidgets.QRadioButton(self.groupBox)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/musical-notes-sign_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioFour.setIcon(icon8)
        self.radioFour.setObjectName("radioFour")
        self.horizontalLayout.addWidget(self.radioFour)
        self.radioThree = QtWidgets.QRadioButton(self.groupBox)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/musical-notes-sign_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioThree.setIcon(icon9)
        self.radioThree.setObjectName("radioThree")
        self.horizontalLayout.addWidget(self.radioThree)
        self.radioTwo = QtWidgets.QRadioButton(self.groupBox)
        self.radioTwo.setIcon(icon6)
        self.radioTwo.setObjectName("radioTwo")
        self.horizontalLayout.addWidget(self.radioTwo)
        self.gridLayout_9.addWidget(self.groupBox, 0, 0, 1, 1)
        self.btnMix = QtWidgets.QPushButton(self.Mix)
        self.btnMix.setMaximumSize(QtCore.QSize(992, 16777215))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/bars-graphic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMix.setIcon(icon10)
        self.btnMix.setObjectName("btnMix")
        self.gridLayout_9.addWidget(self.btnMix, 8, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnImportA = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportA.sizePolicy().hasHeightForWidth())
        self.btnImportA.setSizePolicy(sizePolicy)
        self.btnImportA.setObjectName("btnImportA")
        self.horizontalLayout_2.addWidget(self.btnImportA)
        self.textCurrentFileA = QtWidgets.QLineEdit(self.groupBox_2)
        self.textCurrentFileA.setEnabled(False)
        self.textCurrentFileA.setMaximumSize(QtCore.QSize(980, 16777215))
        self.textCurrentFileA.setInputMask("")
        self.textCurrentFileA.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFileA.setReadOnly(True)
        self.textCurrentFileA.setObjectName("textCurrentFileA")
        self.horizontalLayout_2.addWidget(self.textCurrentFileA)
        self.gridLayout_9.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnImportB = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportB.sizePolicy().hasHeightForWidth())
        self.btnImportB.setSizePolicy(sizePolicy)
        self.btnImportB.setObjectName("btnImportB")
        self.horizontalLayout_3.addWidget(self.btnImportB)
        self.textCurrentFileB = QtWidgets.QLineEdit(self.groupBox_3)
        self.textCurrentFileB.setEnabled(False)
        self.textCurrentFileB.setMaximumSize(QtCore.QSize(980, 16777215))
        self.textCurrentFileB.setInputMask("")
        self.textCurrentFileB.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFileB.setReadOnly(True)
        self.textCurrentFileB.setObjectName("textCurrentFileB")
        self.horizontalLayout_3.addWidget(self.textCurrentFileB)
        self.gridLayout_9.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Mix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(992, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnImportC = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportC.sizePolicy().hasHeightForWidth())
        self.btnImportC.setSizePolicy(sizePolicy)
        self.btnImportC.setObjectName("btnImportC")
        self.horizontalLayout_4.addWidget(self.btnImportC)
        self.textCurrentFileC = QtWidgets.QLineEdit(self.groupBox_4)
        self.textCurrentFileC.setEnabled(False)
        self.textCurrentFileC.setMaximumSize(QtCore.QSize(980, 16777215))
        self.textCurrentFileC.setInputMask("")
        self.textCurrentFileC.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentFileC.setReadOnly(True)
        self.textCurrentFileC.setObjectName("textCurrentFileC")
        self.horizontalLayout_4.addWidget(self.textCurrentFileC)
        self.gridLayout_9.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.stackedCoctail.addWidget(self.Mix)
        self.Separate = QtWidgets.QWidget()
        self.Separate.setObjectName("Separate")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Separate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Separate)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plotMixA = PlotWidget(self.groupBox_7)
        self.plotMixA.setObjectName("plotMixA")
        self.gridLayout_7.addWidget(self.plotMixA, 0, 0, 1, 1)
        self.plotMixB = PlotWidget(self.groupBox_7)
        self.plotMixB.setObjectName("plotMixB")
        self.gridLayout_7.addWidget(self.plotMixB, 0, 1, 1, 1)
        self.plotMixC = PlotWidget(self.groupBox_7)
        self.plotMixC.setObjectName("plotMixC")
        self.gridLayout_7.addWidget(self.plotMixC, 0, 2, 1, 1)
        self.plotMixD = PlotWidget(self.groupBox_7)
        self.plotMixD.setObjectName("plotMixD")
        self.gridLayout_7.addWidget(self.plotMixD, 0, 3, 1, 1)
        self.plotMixE = PlotWidget(self.groupBox_7)
        self.plotMixE.setObjectName("plotMixE")
        self.gridLayout_7.addWidget(self.plotMixE, 0, 4, 1, 1)
        self.btnPlayMixA = QtWidgets.QPushButton(self.groupBox_7)
        self.btnPlayMixA.setIcon(icon5)
        self.btnPlayMixA.setFlat(True)
        self.btnPlayMixA.setObjectName("btnPlayMixA")
        self.gridLayout_7.addWidget(self.btnPlayMixA, 1, 0, 1, 1)
        self.btnPlayMixB = QtWidgets.QPushButton(self.groupBox_7)
        self.btnPlayMixB.setIcon(icon5)
        self.btnPlayMixB.setFlat(True)
        self.btnPlayMixB.setObjectName("btnPlayMixB")
        self.gridLayout_7.addWidget(self.btnPlayMixB, 1, 1, 1, 1)
        self.btnPlayMixC = QtWidgets.QPushButton(self.groupBox_7)
        self.btnPlayMixC.setIcon(icon5)
        self.btnPlayMixC.setFlat(True)
        self.btnPlayMixC.setObjectName("btnPlayMixC")
        self.gridLayout_7.addWidget(self.btnPlayMixC, 1, 2, 1, 1)
        self.btnPlayMixD = QtWidgets.QPushButton(self.groupBox_7)
        self.btnPlayMixD.setIcon(icon5)
        self.btnPlayMixD.setFlat(True)
        self.btnPlayMixD.setObjectName("btnPlayMixD")
        self.gridLayout_7.addWidget(self.btnPlayMixD, 1, 3, 1, 1)
        self.btnPlayMixE = QtWidgets.QPushButton(self.groupBox_7)
        self.btnPlayMixE.setIcon(icon5)
        self.btnPlayMixE.setFlat(True)
        self.btnPlayMixE.setObjectName("btnPlayMixE")
        self.gridLayout_7.addWidget(self.btnPlayMixE, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_9 = QtWidgets.QGroupBox(self.Separate)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnPlaySeparateA = QtWidgets.QPushButton(self.groupBox_9)
        self.btnPlaySeparateA.setIcon(icon5)
        self.btnPlaySeparateA.setFlat(True)
        self.btnPlaySeparateA.setObjectName("btnPlaySeparateA")
        self.gridLayout_8.addWidget(self.btnPlaySeparateA, 1, 0, 1, 1)
        self.btnPlaySeparateB = QtWidgets.QPushButton(self.groupBox_9)
        self.btnPlaySeparateB.setIcon(icon5)
        self.btnPlaySeparateB.setFlat(True)
        self.btnPlaySeparateB.setObjectName("btnPlaySeparateB")
        self.gridLayout_8.addWidget(self.btnPlaySeparateB, 1, 1, 1, 1)
        self.btnPlaySeparateC = QtWidgets.QPushButton(self.groupBox_9)
        self.btnPlaySeparateC.setIcon(icon5)
        self.btnPlaySeparateC.setFlat(True)
        self.btnPlaySeparateC.setObjectName("btnPlaySeparateC")
        self.gridLayout_8.addWidget(self.btnPlaySeparateC, 1, 2, 1, 1)
        self.btnPlaySeparateD = QtWidgets.QPushButton(self.groupBox_9)
        self.btnPlaySeparateD.setIcon(icon5)
        self.btnPlaySeparateD.setFlat(True)
        self.btnPlaySeparateD.setObjectName("btnPlaySeparateD")
        self.gridLayout_8.addWidget(self.btnPlaySeparateD, 1, 3, 1, 1)
        self.btnPlaySeparateE = QtWidgets.QPushButton(self.groupBox_9)
        self.btnPlaySeparateE.setIcon(icon5)
        self.btnPlaySeparateE.setFlat(True)
        self.btnPlaySeparateE.setObjectName("btnPlaySeparateE")
        self.gridLayout_8.addWidget(self.btnPlaySeparateE, 1, 4, 1, 1)
        self.plotSeparateD = PlotWidget(self.groupBox_9)
        self.plotSeparateD.setObjectName("plotSeparateD")
        self.gridLayout_8.addWidget(self.plotSeparateD, 0, 3, 1, 1)
        self.plotSeparateA = PlotWidget(self.groupBox_9)
        self.plotSeparateA.setObjectName("plotSeparateA")
        self.gridLayout_8.addWidget(self.plotSeparateA, 0, 0, 1, 1)
        self.plotSeparateE = PlotWidget(self.groupBox_9)
        self.plotSeparateE.setObjectName("plotSeparateE")
        self.gridLayout_8.addWidget(self.plotSeparateE, 0, 4, 1, 1)
        self.plotSeparateB = PlotWidget(self.groupBox_9)
        self.plotSeparateB.setObjectName("plotSeparateB")
        self.gridLayout_8.addWidget(self.plotSeparateB, 0, 1, 1, 1)
        self.plotSeparateC = PlotWidget(self.groupBox_9)
        self.plotSeparateC.setObjectName("plotSeparateC")
        self.gridLayout_8.addWidget(self.plotSeparateC, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.btnBackMixer = QtWidgets.QPushButton(self.Separate)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/left-arrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackMixer.setIcon(icon11)
        self.btnBackMixer.setFlat(True)
        self.btnBackMixer.setObjectName("btnBackMixer")
        self.verticalLayout_2.addWidget(self.btnBackMixer)
        self.stackedCoctail.addWidget(self.Separate)
        self.gridLayout_6.addWidget(self.stackedCoctail, 0, 0, 1, 1)
        self.toolBox.addItem(self.soundCoctail, icon10, "")
        self.gridLayout_3.addWidget(self.toolBox, 1, 0, 1, 2)
        self.btnStop = QtWidgets.QPushButton(self.soundAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/right-arrowhead-black-square-shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon12)
        self.btnStop.setFlat(True)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_3.addWidget(self.btnStop, 0, 0, 1, 1)
        self.btnHome_1 = QtWidgets.QPushButton(self.soundAnalysis)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnHome_1.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHome_1.setIcon(icon13)
        self.btnHome_1.setFlat(True)
        self.btnHome_1.setObjectName("btnHome_1")
        self.gridLayout_3.addWidget(self.btnHome_1, 0, 1, 1, 1)
        self.stackedHome.addWidget(self.soundAnalysis)
        self.signalAnalysis = QtWidgets.QWidget()
        self.signalAnalysis.setObjectName("signalAnalysis")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.signalAnalysis)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnHome_2 = QtWidgets.QPushButton(self.signalAnalysis)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnHome_2.setFont(font)
        self.btnHome_2.setIcon(icon13)
        self.btnHome_2.setFlat(True)
        self.btnHome_2.setObjectName("btnHome_2")
        self.verticalLayout_5.addWidget(self.btnHome_2)
        self.btnImportSignal = QtWidgets.QPushButton(self.signalAnalysis)
        self.btnImportSignal.setObjectName("btnImportSignal")
        self.verticalLayout_5.addWidget(self.btnImportSignal)
        self.textCurrentSingal = QtWidgets.QLineEdit(self.signalAnalysis)
        self.textCurrentSingal.setEnabled(False)
        self.textCurrentSingal.setInputMask("")
        self.textCurrentSingal.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentSingal.setReadOnly(True)
        self.textCurrentSingal.setObjectName("textCurrentSingal")
        self.verticalLayout_5.addWidget(self.textCurrentSingal)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnSignalScaleDown = QtWidgets.QPushButton(self.signalAnalysis)
        self.btnSignalScaleDown.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("images/minus-sign-of-horizontal-bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSignalScaleDown.setIcon(icon14)
        self.btnSignalScaleDown.setFlat(True)
        self.btnSignalScaleDown.setObjectName("btnSignalScaleDown")
        self.gridLayout_4.addWidget(self.btnSignalScaleDown, 1, 1, 1, 1)
        self.btnSignalScaleUp = QtWidgets.QPushButton(self.signalAnalysis)
        self.btnSignalScaleUp.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("images/plus-sign-of-horizontal-bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSignalScaleUp.setIcon(icon15)
        self.btnSignalScaleUp.setFlat(True)
        self.btnSignalScaleUp.setObjectName("btnSignalScaleUp")
        self.gridLayout_4.addWidget(self.btnSignalScaleUp, 0, 1, 1, 1)
        self.btnSignalLeft = QtWidgets.QPushButton(self.signalAnalysis)
        self.btnSignalLeft.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("images/right-arrowhead.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSignalLeft.setIcon(icon16)
        self.btnSignalLeft.setFlat(True)
        self.btnSignalLeft.setObjectName("btnSignalLeft")
        self.gridLayout_4.addWidget(self.btnSignalLeft, 0, 2, 2, 1)
        self.btnSignalRight = QtWidgets.QPushButton(self.signalAnalysis)
        self.btnSignalRight.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("images/left-arrowhead.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSignalRight.setIcon(icon17)
        self.btnSignalRight.setFlat(True)
        self.btnSignalRight.setObjectName("btnSignalRight")
        self.gridLayout_4.addWidget(self.btnSignalRight, 0, 0, 2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.signalAnalysis)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plotOriginal = PlotWidget(self.groupBox_10)
        self.plotOriginal.setObjectName("plotOriginal")
        self.verticalLayout_3.addWidget(self.plotOriginal)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.signalAnalysis)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plotSeparate = PlotWidget(self.groupBox_11)
        self.plotSeparate.setObjectName("plotSeparate")
        self.verticalLayout_4.addWidget(self.plotSeparate)
        self.verticalLayout_5.addWidget(self.groupBox_11)
        self.stackedHome.addWidget(self.signalAnalysis)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loading = QtWidgets.QPushButton(self.page)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("images/loading-lines-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loading.setIcon(icon18)
        self.loading.setIconSize(QtCore.QSize(500, 500))
        self.loading.setFlat(True)
        self.loading.setObjectName("loading")
        self.verticalLayout.addWidget(self.loading)
        self.stackedHome.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedHome, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedHome.setCurrentIndex(2)
        self.stackedCoctail.setCurrentIndex(0)
        self.checkBox.toggled['bool'].connect(self.btnPlay.setEnabled)
        self.checkBox.toggled['bool'].connect(self.textCurrentFile.setEnabled)
        self.checkBox.toggled['bool'].connect(self.btnPlayVocals.setEnabled)
        self.checkBox.toggled['bool'].connect(self.btnPlayMusic.setEnabled)
        self.radioTwo.toggled['bool'].connect(self.groupBox_4.setHidden)
        self.radioTwo.toggled['bool'].connect(self.groupBox_5.setHidden)
        self.radioTwo.toggled['bool'].connect(self.groupBox_6.setHidden)
        self.radioThree.toggled['bool'].connect(self.groupBox_5.setHidden)
        self.radioThree.toggled['bool'].connect(self.groupBox_6.setHidden)
        self.radioFour.toggled['bool'].connect(self.groupBox_6.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotMixC.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotMixD.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotMixE.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotSeparateC.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotSeparateD.setHidden)
        self.radioTwo.toggled['bool'].connect(self.plotSeparateE.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlayMixC.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlayMixD.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlayMixE.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlaySeparateC.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlaySeparateD.setHidden)
        self.radioTwo.toggled['bool'].connect(self.btnPlaySeparateE.setHidden)
        self.radioThree.toggled['bool'].connect(self.plotMixD.setHidden)
        self.radioThree.toggled['bool'].connect(self.plotMixE.setHidden)
        self.radioThree.toggled['bool'].connect(self.plotSeparateD.setHidden)
        self.radioThree.toggled['bool'].connect(self.plotSeparateE.setHidden)
        self.radioThree.toggled['bool'].connect(self.btnPlayMixD.setHidden)
        self.radioThree.toggled['bool'].connect(self.btnPlayMixE.setHidden)
        self.radioThree.toggled['bool'].connect(self.btnPlaySeparateD.setHidden)
        self.radioThree.toggled['bool'].connect(self.btnPlaySeparateE.setHidden)
        self.radioFour.toggled['bool'].connect(self.plotMixE.setHidden)
        self.radioFour.toggled['bool'].connect(self.plotSeparateE.setHidden)
        self.radioFour.toggled['bool'].connect(self.btnPlayMixE.setHidden)
        self.radioFour.toggled['bool'].connect(self.btnPlaySeparateE.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICA"))
        self.label_2.setText(_translate("MainWindow", "Signal Analysis"))
        self.label.setText(_translate("MainWindow", "Sound Analysis"))
        self.btnPlayMusic.setText(_translate("MainWindow", "-Music-"))
        self.btnPlayMusic.setShortcut(_translate("MainWindow", "Space"))
        self.btnPlayVocals.setText(_translate("MainWindow", "-Vocals-"))
        self.btnPlayVocals.setShortcut(_translate("MainWindow", "Space"))
        self.textCurrentFile.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFile.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.btnPlay.setText(_translate("MainWindow", "Play"))
        self.btnPlay.setShortcut(_translate("MainWindow", "Space"))
        self.btnImportSong.setText(_translate("MainWindow", "Import..."))
        self.checkBox.setText(_translate("MainWindow", "E"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Result"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.soundSong), _translate("MainWindow", "Song Separation (Music-Vocals)"))
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.soundSong), _translate("MainWindow", "This part represents Problem 4 - Part A."))
        self.groupBox_6.setTitle(_translate("MainWindow", "SourceE"))
        self.btnImportE.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFileE.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFileE.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "SourceD"))
        self.btnImportD.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFileD.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFileD.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox.setTitle(_translate("MainWindow", "Sources"))
        self.radioFive.setText(_translate("MainWindow", "Five Sources"))
        self.radioFour.setText(_translate("MainWindow", "Four Sources"))
        self.radioThree.setText(_translate("MainWindow", "Three Sources"))
        self.radioTwo.setText(_translate("MainWindow", "Two Sources"))
        self.btnMix.setText(_translate("MainWindow", "Start"))
        self.groupBox_2.setTitle(_translate("MainWindow", "SourceA"))
        self.btnImportA.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFileA.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFileA.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "SourceB"))
        self.btnImportB.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFileB.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFileB.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "SourceC"))
        self.btnImportC.setText(_translate("MainWindow", "Import..."))
        self.textCurrentFileC.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentFileC.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.groupBox_7.setTitle(_translate("MainWindow", "Mixes"))
        self.btnPlayMixA.setText(_translate("MainWindow", "Mix A"))
        self.btnPlayMixB.setText(_translate("MainWindow", "Mix B"))
        self.btnPlayMixC.setText(_translate("MainWindow", "Mix C"))
        self.btnPlayMixD.setText(_translate("MainWindow", "Mix D"))
        self.btnPlayMixE.setText(_translate("MainWindow", "Mix E"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Separates"))
        self.btnPlaySeparateA.setText(_translate("MainWindow", "Separate A"))
        self.btnPlaySeparateB.setText(_translate("MainWindow", "Separate B"))
        self.btnPlaySeparateC.setText(_translate("MainWindow", "Separate C"))
        self.btnPlaySeparateD.setText(_translate("MainWindow", "Separate D"))
        self.btnPlaySeparateE.setText(_translate("MainWindow", "Separate E"))
        self.btnBackMixer.setText(_translate("MainWindow", "Back to Mixer"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.soundCoctail), _translate("MainWindow", "Coctail Party (Sources Separation)"))
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.soundCoctail), _translate("MainWindow", "This part represents Problem 4 - Part B."))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnHome_1.setText(_translate("MainWindow", "Home"))
        self.btnHome_2.setText(_translate("MainWindow", "Home"))
        self.btnImportSignal.setText(_translate("MainWindow", "Import..."))
        self.textCurrentSingal.setText(_translate("MainWindow", "Please select audio file..."))
        self.textCurrentSingal.setPlaceholderText(_translate("MainWindow", "Please select audio file or record new file..."))
        self.btnSignalScaleDown.setShortcut(_translate("MainWindow", "-"))
        self.btnSignalScaleUp.setShortcut(_translate("MainWindow", "+"))
        self.btnSignalLeft.setShortcut(_translate("MainWindow", "Right"))
        self.btnSignalRight.setShortcut(_translate("MainWindow", "Left"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Original Signal"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Separated Signal"))

from pyqtgraph import PlotWidget
